engines:
  #
  # -------------------------------------------------
  # Shotgun Desktop
  # -------------------------------------------------
  tk-desktop:
    apps:
      tk-multi-launchrez_maya_2019: '@launch_rez_maya_2019'  # Insert this for rez Maya 2019!
  #
  # -------------------------------------------------
  # Shell Engine (tank command)
  # -------------------------------------------------
  tk-shell:
    apps:
      tk-multi-launchrez_maya_2019: '@launch_rez_maya_2019'  # Insert this for rez Maya 2019!